Committing cgiwrap-3.3 source tree

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -20,7 +20,7 @@
 
 # $Id$
 #
-# Generated on Fri Mar 29 21:05:02 CST 1996 [metaconfig 3.0 PL60]
+# Generated on Tue Apr  9 11:05:04 CDT 1996 [metaconfig 3.0 PL60]
 
 cat >/tmp/c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -228,8 +228,10 @@ d_conf_check_scruid=''
 d_check_httpd_user=''
 d_httpd_user=''
 httpd_user=''
-d_log_requests=''
-log_file=''
+conf_log_label=''
+conf_log_logfile=''
+d_conf_log_usefile=''
+d_conf_log_usesyslog=''
 d_conf_subdirs=''
 d_conf_redir_stderr=''
 d_conf_useset=''
@@ -251,6 +253,9 @@ d_setreuid=''
 d_setrgid=''
 d_setruid=''
 d_strdup=''
+d_syslog=''
+syslogc=''
+syslogo=''
 d_system=''
 d_initgroups=''
 d_setgid=''
@@ -1164,10 +1169,8 @@ on, cgiwrap will exit.
 EOM
 
 case "$d_check_httpd_user" in
-'')     dflt="y" ;;
-define)	dflt="y" ;;
 undef)	dflt="n" ;;
-*)      dflt="$d_check_httpd_user" ;;
+*)      dflt="y" ;;
 esac
 
 rp="Verify cgiwrap executed by server?"
@@ -1448,6 +1451,7 @@ EOM
 esac
 
 
+
 case "$d_conf_allowfile$d_conf_denyfile" in
 undefdefine|defineundef|definedefine)
 
@@ -1489,6 +1493,9 @@ EOM
 	eval $setvar
 	
 	;;
+
+*)
+	d_conf_checkhost="undef"
 esac
 $cat <<'EOM'
 
@@ -3054,6 +3061,123 @@ eval $setvar
 
 esac
 
+
+$cat <<'EOM'
+
+CGIwrap can log all incoming CGI requests to a file or syslog. This allows
+you to keep track of who is using CGIwrap on your system independent of
+web server logging. The time, date, remote host, user, script name,
+authenticated userid, and a short message are logged to this file. 
+
+If you choose to log to syslog, cgiwrap will log using facility 
+LOG_DAEMON, priority LOG_INFO, and will log the pid. The syslog message 
+will have the format: "[label] user, script, host, address, user, message"
+
+EOM
+
+#
+# Ask about logging to syslog
+#
+
+case "$d_conf_log_usesyslog" in
+undef) dflt='n' ;;
+*) dflt="y"
+esac
+
+rp="Log requests to syslog?"
+. ./myread
+
+case "$ans" in
+y|Y) val="$define" ;;
+*) val="$undef" ;;
+esac
+
+set d_conf_log_usesyslog
+eval $setvar
+
+
+case "$d_conf_log_usesyslog" in
+define) 
+$cat <<'EOM'
+
+Since some sites will have multiple instances of cgiwrap running on a 
+single machine, it is often handy to be able to differentiate between 
+them. Since there is only one type of message for syslog, cgiwrap allows 
+you to assign a label to any messages that are generated by this copy of 
+cgiwrap. 
+
+For example, if you are running an authenticated cgiwrap on a server on 
+port 2000, you might label it "auth-2000". You can leave the label blank if 
+this feature is not of use to you.
+
+EOM
+
+#
+# Get the log file name
+#
+
+	case "$conf_log_label" in
+	'')	dflt="" ;;
+	*)	dflt="$conf_log_logfile" ;;
+	esac
+
+	rp="What label should be assigned?"
+	. ./myread
+
+	conf_log_label="$ans"
+;;
+
+*) ;;
+esac
+
+
+#
+# Check about file, and prompt for filename if necessary
+#
+
+case "$d_conf_log_usefile" in
+undef) dflt='n' ;;
+*) dflt="y"
+esac
+
+rp="Log requests to a file?"
+. ./myread
+
+case "$ans" in
+y|Y) val="$define" ;;
+*) val="$undef" ;;
+esac
+
+set d_conf_log_usefile
+eval $setvar
+
+
+case "$d_conf_log_usefile" in
+define) 
+$cat <<'EOM'
+
+Now I need to know what file name you would like cgiwrap to log to. 
+
+EOM
+
+#
+# Get the log file name
+#
+
+	case "$conf_log_logfile" in
+	'')	dflt="/usr/adm/cgiwrap.log" ;;
+	*)	dflt="$conf_log_logfile" ;;
+	esac
+
+	rp="What file should cgiwrap log to?"
+	. ./myread
+
+	conf_log_logfile="$ans"
+;;
+
+*) ;;
+esac
+
 $cat <<'EOM'
 
 CGIwrap has the capability of automatically redirecting the stderr output
@@ -3360,61 +3484,6 @@ in this Configure script.
 
 EOM
 
-$cat <<'EOM'
-
-Answer the next question yes if you want cgiwrap to log all CGI script
-requests to a file. The time, date, remote host, user, script name, 
-authenticated userid, and a short message are logged to this file.
-
-EOM
-
-case "$d_conf_log_requests" in
-define) dflt='y' ;;
-undef) dflt='n' ;;
-*) dflt="y"
-esac
-
-rp="Log Requests?"
-. ./myread
-
-case "$ans" in
-y|Y) val="$define" ;;
-*) val="$undef" ;;
-esac
-
-set d_log_requests
-eval $setvar
-
-
-
-case "$d_log_requests" in
-define) 
-$cat <<'EOM'
-
-Now I need to know what file name you would like cgiwrap to log to. 
-
-EOM
-
-
-#
-# Get the log file name
-#
-
-	case "$log_file" in
-	'')	dflt="/usr/adm/cgiwrap.log" ;;
-	*)	dflt="$log_file" ;;
-	esac
-
-	rp="What file should cgiwrap log to?"
-	. ./myread
-
-	log_file="$ans"
-
-;;
-
-*) ;;
-esac
-
 : see if sigset exists
 set sigset d_sigset
 eval $inlibc
@@ -3422,6 +3491,83 @@ eval $inlibc
 : see if strdup exists
 set strdup d_strdup
 eval $inlibc
+
+: determine filename position in cpp output
+echo " "
+echo "Computing filename position in cpp output for #include directives..." >&4
+echo '#include <stdio.h>' > foo.c
+$cat >fieldn <<EOF
+$startsh
+$cppstdin $cppflags $cppminus <foo.c 2>/dev/null | \
+$grep '^[ 	]*#.*stdio\.h' | \
+while read cline; do
+	pos=1
+	set \$cline
+	while $test \$# -gt 0; do
+		if $test -r \`echo \$1 | $tr -d '"'\`; then
+			echo "\$pos"
+			exit 0
+		fi
+		shift
+		pos=\`expr \$pos + 1\`
+	done
+done
+EOF
+chmod +x fieldn
+fieldn=`./fieldn`
+$rm -f foo.c fieldn
+case $fieldn in
+'') pos='???';;
+1) pos=first;;
+2) pos=second;;
+3) pos=third;;
+*) pos="${fieldn}th";;
+esac
+echo "Your cpp writes the filename in the $pos field of the line."
+
+: locate header file
+$cat >findhdr <<EOF
+$startsh
+wanted=\$1
+name=''
+if test -f $usrinc/\$wanted; then
+	echo "$usrinc/\$wanted"
+	exit 0
+fi
+awkprg='{ print \$$fieldn }'
+echo "#include <\$wanted>" > foo\$\$.c
+$cppstdin $cppminus $cppflags < foo\$\$.c 2>/dev/null | \
+$grep "^[ 	]*#.*\$wanted" | \
+while read cline; do
+	name=\`echo \$cline | $awk "\$awkprg" | $tr -d '"'\`
+	case "\$name" in
+	*/\$wanted) echo "\$name"; exit 0;;
+	*) name='';;
+	esac;
+done;
+$rm -f foo\$\$.c;
+case "\$name" in
+'') exit 1;;
+esac
+EOF
+chmod +x findhdr
+
+: see if syslog is available
+echo " "
+if $test `./findhdr syslog.h` && \
+	(set syslog val -f d_syslog; eval $csym; $val); then
+	echo "syslog() found." >&4
+	val="$define"
+	syslogc=''
+	syslogo=''
+else
+	echo "syslog() not found in your C library--using ./syslog.c." >&4
+	val="$undef"
+	syslogc='syslog.c'
+	syslogo='syslog.o'
+fi
+set d_syslog
+eval $setvar
 
 : check for void type
 echo " "
@@ -3511,66 +3657,6 @@ rp="Your void support flags add up to what?"
 . ./myread
 voidflags="$ans"
 $rm -f try.* .out
-
-: determine filename position in cpp output
-echo " "
-echo "Computing filename position in cpp output for #include directives..." >&4
-echo '#include <stdio.h>' > foo.c
-$cat >fieldn <<EOF
-$startsh
-$cppstdin $cppflags $cppminus <foo.c 2>/dev/null | \
-$grep '^[ 	]*#.*stdio\.h' | \
-while read cline; do
-	pos=1
-	set \$cline
-	while $test \$# -gt 0; do
-		if $test -r \`echo \$1 | $tr -d '"'\`; then
-			echo "\$pos"
-			exit 0
-		fi
-		shift
-		pos=\`expr \$pos + 1\`
-	done
-done
-EOF
-chmod +x fieldn
-fieldn=`./fieldn`
-$rm -f foo.c fieldn
-case $fieldn in
-'') pos='???';;
-1) pos=first;;
-2) pos=second;;
-3) pos=third;;
-*) pos="${fieldn}th";;
-esac
-echo "Your cpp writes the filename in the $pos field of the line."
-
-: locate header file
-$cat >findhdr <<EOF
-$startsh
-wanted=\$1
-name=''
-if test -f $usrinc/\$wanted; then
-	echo "$usrinc/\$wanted"
-	exit 0
-fi
-awkprg='{ print \$$fieldn }'
-echo "#include <\$wanted>" > foo\$\$.c
-$cppstdin $cppminus $cppflags < foo\$\$.c 2>/dev/null | \
-$grep "^[ 	]*#.*\$wanted" | \
-while read cline; do
-	name=\`echo \$cline | $awk "\$awkprg" | $tr -d '"'\`
-	case "\$name" in
-	*/\$wanted) echo "\$name"; exit 0;;
-	*) name='';;
-	esac;
-done;
-$rm -f foo\$\$.c;
-case "\$name" in
-'') exit 1;;
-esac
-EOF
-chmod +x findhdr
 
 : define an alternate in-header-list? function
 inhdr='echo " "; td=$define; tu=$undef; yyy=$@;
@@ -3960,8 +4046,10 @@ d_conf_check_scruid='$d_conf_check_scruid'
 d_check_httpd_user='$d_check_httpd_user'
 d_httpd_user='$d_httpd_user'
 httpd_user='$httpd_user'
-d_log_requests='$d_log_requests'
-log_file='$log_file'
+conf_log_label='$conf_log_label'
+conf_log_logfile='$conf_log_logfile'
+d_conf_log_usefile='$d_conf_log_usefile'
+d_conf_log_usesyslog='$d_conf_log_usesyslog'
 d_conf_subdirs='$d_conf_subdirs'
 d_conf_redir_stderr='$d_conf_redir_stderr'
 d_conf_useset='$d_conf_useset'
@@ -3983,6 +4071,9 @@ d_setreuid='$d_setreuid'
 d_setrgid='$d_setrgid'
 d_setruid='$d_setruid'
 d_strdup='$d_strdup'
+d_syslog='$d_syslog'
+syslogc='$syslogc'
+syslogo='$syslogo'
 d_system='$d_system'
 d_initgroups='$d_initgroups'
 d_setgid='$d_setgid'
